"""
seed_data_challenges.py
------------------------
WHAT: The raw content for the 5 levels and their challenges (8 each = 40
      total). ALL scenarios are safe fictional simulations — fictional
      organizations (NovaBank, QuickShop, ExampleMail, BrightJobs, etc.),
      example/test-reserved domains, no real people's data, no real
      phishing infrastructure.
WHERE: seed/seed_data_challenges.py (data only, no DB calls — imported by
       seed/seed_all.py which does the actual inserts)
"""

LEVELS = [
    {
        "number": 1, "key": "phishing_hunter", "name": "Phishing Hunter",
        "description": "Spot suspicious senders, urgency, attachments, credential/OTP requests, and impersonation in emails.",
    },
    {
        "number": 2, "key": "url_detective", "name": "URL Detective",
        "description": "Identify suspicious domains, look-alikes, excessive subdomains, shorteners, and raw-IP URLs.",
    },
    {
        "number": 3, "key": "account_guardian", "name": "Account Guardian",
        "description": "Recognize weak passwords, password reuse, and the value of passphrases and MFA.",
    },
    {
        "number": 4, "key": "scam_spotter", "name": "Scam Spotter",
        "description": "Spot fictional SMS, WhatsApp, bank/KYC, job-offer, delivery, support, prize, and payment scams.",
    },
    {
        "number": 5, "key": "cyber_escape", "name": "Cyber Escape",
        "description": "A final multi-stage scenario combining everything you've learned. Escape the scam!",
    },
]

# Each challenge: scenario_type, prompt, question_text, difficulty, hint,
# correct_explanation, warning_signs (\n separated), recommended_action,
# options: list of (text, is_correct)

CHALLENGES_BY_LEVEL_KEY = {
    "phishing_hunter": [
        {
            "scenario_type": "email", "difficulty": "easy",
            "prompt": "From: security@novabank-alerts.info\nSubject: URGENT: Your NovaBank account will be suspended!\n\nDear Customer,\nWe detected unusual activity. Verify your account within 24 hours by clicking the link below or your account will be suspended.\n[Verify Now]",
            "question_text": "Is this email safe to act on?",
            "hint_text": "Look closely at the sender's domain — is it really NovaBank's official domain?",
            "correct_explanation": "The sender domain 'novabank-alerts.info' is not NovaBank's real domain, and the email uses urgency and a generic greeting to pressure quick action.",
            "warning_signs": "Suspicious sender domain\nUrgent threatening language\nGeneric 'Dear Customer' greeting\nLink asking to 'verify' account",
            "recommended_action": "Do not click the link. Log in to NovaBank directly via its official app or website to check your account.",
            "options": [("This is a phishing email — do not click the link", True),
                        ("This is safe because it mentions my bank's name", False),
                        ("I should click the link quickly before my account is suspended", False)],
        },
        {
            "scenario_type": "email", "difficulty": "easy",
            "prompt": "From: hr@brightjobs-careers.com\nSubject: Job Offer - Immediate Start\n\nCongratulations! You've been selected. Please reply with your bank account details and a copy of your ID to process your first paycheck.",
            "question_text": "What should you do with this email?",
            "hint_text": "Legitimate employers don't ask for bank details before you've even interviewed.",
            "correct_explanation": "No legitimate employer asks for bank account numbers or ID copies via unsolicited email before any interview or offer letter process.",
            "warning_signs": "Unsolicited job offer\nRequests sensitive financial/ID info upfront\nNo interview process mentioned\nUrgency ('immediate start')",
            "recommended_action": "Don't reply with personal or financial information. Verify the company independently through its official careers page.",
            "options": [("Reply with the requested bank details since it's a real opportunity", False),
                        ("Recognize this as a likely job scam and do not share information", True),
                        ("Forward my ID to speed up the process", False)],
        },
        {
            "scenario_type": "email", "difficulty": "medium",
            "prompt": "From: it-support@examplemail-helpdesk.net\nSubject: Password Expiring Today\n\nYour ExampleMail password expires today. Enter your current password here to keep your account active: [Renew Password]",
            "question_text": "Is this a legitimate password renewal request?",
            "hint_text": "Would your real email provider ever ask you to type your password into a link from an email?",
            "correct_explanation": "Legitimate services never ask you to enter your current password through an emailed link — this is a classic credential-harvesting attempt.",
            "warning_signs": "Requests current password via link\nUrgency ('expires today')\nSender domain doesn't match the real service",
            "recommended_action": "Don't click the link or enter your password. Go to the real service directly if you're worried about your password.",
            "options": [("Enter my password on the linked page to avoid losing access", False),
                        ("This is a phishing attempt — don't enter my password there", True),
                        ("Reply asking for more details first", False)],
        },
        {
            "scenario_type": "email", "difficulty": "medium",
            "prompt": "From: ceo.office@yourcompany-corp.co\nSubject: Quick favor\n\nHi, I'm in a meeting and can't talk. I need you to buy 5 gift cards for a client and send me the codes right away. I'll reimburse you.",
            "question_text": "Your 'CEO' emails you this urgent request. What do you do?",
            "hint_text": "This is a classic Business Email Compromise (BEC) / CEO fraud pattern.",
            "correct_explanation": "This is a classic impersonation ('CEO fraud') scam: urgency, unusual request, gift cards (untraceable), and unavailability to verify by phone.",
            "warning_signs": "Impersonates an authority figure\nUnusual request (gift cards)\nCreates urgency and unavailability\nSlightly off sender domain",
            "recommended_action": "Verify directly with the person through a known phone number or in person before taking any action — never through the email itself.",
            "options": [("Buy the gift cards immediately since it's the CEO", False),
                        ("Call the CEO directly using a known number to verify first", True),
                        ("Reply to the email asking if they're sure", False)],
        },
        {
            "scenario_type": "email", "difficulty": "medium",
            "prompt": "From: shipping@quickshop-delivery.support\nSubject: Delivery Failed - Attachment Enclosed\n\nWe couldn't deliver your package. See the attached invoice_details.zip for redelivery instructions.",
            "question_text": "Should you open the attachment?",
            "hint_text": "Unexpected .zip attachments are a common malware delivery method.",
            "correct_explanation": "Unexpected zip/executable attachments, especially from delivery notifications you didn't expect, are a common way malware is spread.",
            "warning_signs": "Unexpected attachment\n.zip file format\nNo order/tracking number referenced\nGeneric delivery-failure pretext",
            "recommended_action": "Don't open the attachment. Check tracking directly on the courier's official website using an order number you have on file.",
            "options": [("Open the zip file to see the delivery details", False),
                        ("Don't open it — verify via the courier's official site instead", True),
                        ("Reply asking them to resend the package", False)],
        },
        {
            "scenario_type": "email", "difficulty": "hard",
            "prompt": "From: security-team@paypaI-secure.com\nSubject: Confirm your identity\n\nDear User, we need you to confirm your identity by entering your password and OTP at the secure link below within 1 hour.",
            "question_text": "Look closely at the sender domain. What's going on?",
            "hint_text": "Look very carefully at every character in the domain name.",
            "correct_explanation": "The domain uses a capital 'I' instead of a lowercase 'l' ('paypaI' vs 'paypal') — a classic look-alike/typosquatting trick, combined with a request for password AND OTP.",
            "warning_signs": "Look-alike domain (character substitution)\nRequests password and OTP together\nTight urgency window (1 hour)\nGeneric greeting",
            "recommended_action": "Don't click or enter anything. Go to the real service directly by typing the URL yourself.",
            "options": [("The domain looks fine, I'll proceed", False),
                        ("This is a look-alike domain trying to steal my credentials", True),
                        ("I'll enter my password but not the OTP", False)],
        },
        {
            "scenario_type": "email", "difficulty": "hard",
            "prompt": "From: no-reply@examplecloud-storage.com\nSubject: Someone shared a document with you\n\nA colleague shared 'Q3_Budget.xlsx' with you. Click to view. You'll be asked to sign in with your work email and password.",
            "question_text": "What's the safest way to handle this?",
            "hint_text": "Fake document-share notifications are a common way to harvest work credentials.",
            "correct_explanation": "Fake 'document shared' notifications that lead to a login page are a common credential-phishing pattern, especially in workplace settings.",
            "warning_signs": "Unexpected file-share notification\nRequests work email + password to 'view'\nUnfamiliar sender domain",
            "recommended_action": "Verify with the colleague directly through a known channel (chat, phone) before clicking, and never enter your work password on an unfamiliar page.",
            "options": [("Sign in immediately to view the shared document", False),
                        ("Confirm with the colleague directly before clicking anything", True),
                        ("Forward it to IT without checking first", False)],
        },
        {
            "scenario_type": "email", "difficulty": "hard",
            "prompt": "From: rewards@novabank-alerts.info\nSubject: You've earned a cashback reward of $50!\n\nClaim your reward by confirming your card number and CVV within 24 hours.",
            "question_text": "Should you claim this reward?",
            "hint_text": "Would a real bank ever ask for your CVV to give you a reward?",
            "correct_explanation": "No legitimate bank or rewards program ever needs your CVV to credit a reward — CVV requests are almost always a red flag for card fraud.",
            "warning_signs": "Unsolicited reward claim\nRequests card number + CVV\nUrgency (24 hours)\nSuspicious sender domain",
            "recommended_action": "Don't provide card details. Log in to your real bank account directly to check for any legitimate rewards.",
            "options": [("Provide the card number and CVV to claim the reward", False),
                        ("Recognize this as a scam and don't share card details", True),
                        ("Only provide the card number, not the CVV", False)],
        },
    ],
    "url_detective": [
        {
            "scenario_type": "url", "difficulty": "easy",
            "prompt": "http://192.168.45.201/login/account/verify",
            "question_text": "Would you enter your login details on this URL?",
            "hint_text": "Look at what's used instead of a domain name.",
            "correct_explanation": "This URL uses a raw IP address instead of a domain name — legitimate services almost always use a proper, recognizable domain.",
            "warning_signs": "Raw IP address instead of a domain\nNo HTTPS\nGeneric 'login/verify' path",
            "recommended_action": "Don't enter any information. Navigate to the real service using its known domain name instead.",
            "options": [("No — raw IP addresses like this are a red flag", True),
                        ("Yes, IP addresses are just as safe as domain names", False)],
        },
        {
            "scenario_type": "url", "difficulty": "easy",
            "prompt": "https://www.examplebank.com.account-verify-secure.tk/login",
            "question_text": "Is 'examplebank.com' actually the domain being visited here?",
            "hint_text": "The REAL domain is whatever comes right before the final '/' section — read from the right.",
            "correct_explanation": "The actual domain is 'account-verify-secure.tk' — 'examplebank.com' is just a subdomain-like prefix used to trick you into thinking it's the real bank.",
            "warning_signs": "Brand name used as a fake subdomain\nUnusual TLD (.tk)\nExtra 'verify-secure' keywords",
            "recommended_action": "Don't trust the presence of a familiar name anywhere in the URL — check the actual registrable domain carefully.",
            "options": [("Yes, I see 'examplebank.com' so it's safe", False),
                        ("No — the real domain is 'account-verify-secure.tk', not examplebank.com", True)],
        },
        {
            "scenario_type": "url", "difficulty": "medium",
            "prompt": "https://bit.ly/novabank-verify-49x",
            "question_text": "A message asks you to click this shortened link to 'verify your account'. What's the concern?",
            "hint_text": "What does a URL shortener hide from you?",
            "correct_explanation": "URL shorteners hide the actual destination domain, making it impossible to verify where you'll really end up before clicking.",
            "warning_signs": "URL shortening service\nCombined with an account-verification pretext\nCan't see the real destination",
            "recommended_action": "Avoid clicking shortened links from unsolicited messages. Go to the real service directly instead.",
            "options": [("It's fine, shortened links are always safe", False),
                        ("The real destination is hidden — treat it with caution", True)],
        },
        {
            "scenario_type": "url", "difficulty": "medium",
            "prompt": "http://secure.login.account.update.novabank.verify-info.top/",
            "question_text": "What's suspicious about this URL's structure?",
            "hint_text": "Count how many dot-separated parts come before the real domain.",
            "correct_explanation": "This URL uses an excessive number of subdomains packed with trust-building keywords (secure, login, account, update, verify) to look legitimate, with the real domain being 'verify-info.top'.",
            "warning_signs": "Excessive subdomains\nKeyword stuffing (secure, login, verify)\nUnusual TLD (.top)\nNo HTTPS",
            "recommended_action": "Don't be fooled by familiar words packed into the URL — check the actual base domain.",
            "options": [("The extra words make it more trustworthy", False),
                        ("Excessive subdomains and keyword-stuffing are a red flag", True)],
        },
        {
            "scenario_type": "url", "difficulty": "medium",
            "prompt": "https://quickshop-support.com/track?order=99213&redirect=http://malicious-test.invalid/collect",
            "question_text": "What should catch your attention in this URL's query string?",
            "hint_text": "Look at what the 'redirect' parameter points to.",
            "correct_explanation": "The URL contains a redirect parameter pointing to a completely different, suspicious domain — a common technique to send you somewhere unexpected after you trust the first domain.",
            "warning_signs": "Embedded redirect parameter to a different domain\nThe redirect target looks suspicious",
            "recommended_action": "Be cautious of URLs with embedded redirect parameters pointing elsewhere — don't assume the first domain is where you'll end up.",
            "options": [("The order number makes this look legitimate, it's fine", False),
                        ("The redirect parameter pointing elsewhere is a red flag", True)],
        },
        {
            "scenario_type": "url", "difficulty": "hard",
            "prompt": "https://arnaz0n-deals.com/prime/renew",
            "question_text": "What pattern is being used in this domain name?",
            "hint_text": "Say the domain name out loud, ignoring how it's spelled.",
            "correct_explanation": "This is typosquatting/look-alike domain: 'arnaz0n' visually resembles a well-known brand using character substitutions (rn instead of m, 0 instead of o).",
            "warning_signs": "Character-substitution look-alike domain\nUnrelated TLD/structure\nBrand-adjacent path ('/prime/renew')",
            "recommended_action": "Type the real, known domain directly into your browser instead of trusting links that merely look similar.",
            "options": [("This looks like the real brand's domain, it's safe", False),
                        ("This is a typosquatted look-alike domain — avoid it", True)],
        },
        {
            "scenario_type": "url", "difficulty": "hard",
            "prompt": "http://novabank.com@account-verify-test.invalid/secure/login",
            "question_text": "Where does this URL actually take you?",
            "hint_text": "In a URL, everything before an '@' symbol is just a username — it's not the domain.",
            "correct_explanation": "Everything before the '@' is treated as a username by browsers — the ACTUAL destination is 'account-verify-test.invalid', not novabank.com. This is the classic '@' trick to hide the real destination.",
            "warning_signs": "'@' symbol used to disguise the real host\nReal destination is an unrelated domain",
            "recommended_action": "Never trust a brand name that appears before an '@' symbol in a URL — it's not the actual destination.",
            "options": [("It takes me to novabank.com since that's listed first", False),
                        ("It actually takes me to 'account-verify-test.invalid'", True)],
        },
        {
            "scenario_type": "url", "difficulty": "hard",
            "prompt": "http://203.0.113.77:8080/update.exe",
            "question_text": "A pop-up says you need to click this link to 'update your security software'. Assess it.",
            "hint_text": "Look at the IP, the port, and the file extension together.",
            "correct_explanation": "This combines multiple high-risk signals: a raw IP address, an unusual port, and a link directly to a downloadable .exe file — a strong malware-delivery pattern.",
            "warning_signs": "Raw IP address\nUnusual port number\nDirect executable (.exe) download link\nNo HTTPS",
            "recommended_action": "Do not download or run this file. Get software updates only from the official vendor's website or your OS's built-in updater.",
            "options": [("Download it to fix my security software quickly", False),
                        ("This has multiple serious red flags — do not download it", True)],
        },
    ],
    "account_guardian": [
        {
            "scenario_type": "password", "difficulty": "easy",
            "prompt": "Password: password123",
            "question_text": "Rate this password.",
            "hint_text": "Is this one of the most commonly used passwords in the world?",
            "correct_explanation": "\"password123\" is one of the most commonly guessed/leaked passwords in the world and offers essentially no protection.",
            "warning_signs": "Common dictionary word\nPredictable number suffix\nNo symbols or mixed complexity",
            "recommended_action": "Use a long, unique passphrase instead, and enable MFA wherever possible.",
            "options": [("Weak — it's one of the most common passwords", True),
                        ("Strong — it has letters and numbers", False)],
        },
        {
            "scenario_type": "password", "difficulty": "easy",
            "prompt": "You use \"Summer2024!\" for your email, bank, and shopping accounts.",
            "question_text": "What's the main risk here?",
            "hint_text": "What happens if just ONE of those three sites gets breached?",
            "correct_explanation": "Reusing the same password across multiple accounts means a breach at any ONE of those services exposes ALL of your accounts (credential stuffing).",
            "warning_signs": "Same password reused across multiple accounts\nPredictable pattern (season + year + symbol)",
            "recommended_action": "Use a different, unique password for every account — a password manager makes this practical.",
            "options": [("No risk — it's a strong-looking password", False),
                        ("Password reuse means one breach compromises all three accounts", True)],
        },
        {
            "scenario_type": "password", "difficulty": "medium",
            "prompt": "Option A: \"Tr0ub4dor&3\"   Option B: \"correct-horse-battery-staple-42\"",
            "question_text": "Which password is generally stronger against modern cracking methods, and why?",
            "hint_text": "Think about total length, not just character complexity.",
            "correct_explanation": "Option B, a long random passphrase, is generally stronger — length matters more than complex-looking short passwords, and passphrases are also easier for humans to remember.",
            "warning_signs": "Short 'complex-looking' passwords can still be short in total length\nHumans often reuse short complex passwords because they're hard to remember",
            "recommended_action": "Prefer long, unique passphrases (4+ random words or 16+ characters) over short complex-looking ones.",
            "options": [("Option A, because it has more symbols", False),
                        ("Option B, because its greater length makes it harder to crack", True)],
        },
        {
            "scenario_type": "password", "difficulty": "medium",
            "prompt": "Your bank account offers to enable a second step (an app code) in addition to your password when logging in.",
            "question_text": "Should you enable this (multi-factor authentication / MFA)?",
            "hint_text": "What happens if your password alone gets stolen, but MFA is on?",
            "correct_explanation": "MFA means that even if your password is stolen, an attacker still can't log in without the second factor — it's one of the single most effective account-security measures available.",
            "warning_signs": "N/A — this is a positive security practice, not a threat",
            "recommended_action": "Enable MFA on every account that offers it, especially email, banking, and social media.",
            "options": [("Yes, enable it — it significantly improves account security", True),
                        ("No, it's an unnecessary extra step", False)],
        },
        {
            "scenario_type": "password", "difficulty": "medium",
            "prompt": "You get a text: \"Your account password will expire. Reply with your current password to keep it active.\"",
            "question_text": "How should you respond?",
            "hint_text": "Does any legitimate service ever ask you to text them your password?",
            "correct_explanation": "No legitimate organization will ever ask you to send your password via text message — this is a direct credential-theft attempt.",
            "warning_signs": "Direct request for your actual password\nVia an unusual channel (SMS)\nUrgency ('will expire')",
            "recommended_action": "Never share your password with anyone, through any channel. Ignore and report the message.",
            "options": [("Reply with the password to keep my account active", False),
                        ("Never reply — no legitimate service asks for your password this way", True)],
        },
        {
            "scenario_type": "password", "difficulty": "hard",
            "prompt": "You want a password that's both strong AND memorable, without writing it down.",
            "question_text": "Which strategy best achieves this?",
            "hint_text": "Random words you can visualize are easier to recall than random characters.",
            "correct_explanation": "A passphrase built from several unrelated random words (e.g. 'purple-tractor-lagoon-42') is both long/strong and easier for humans to remember than random character strings.",
            "warning_signs": "N/A — this question is about good practice, not a threat",
            "recommended_action": "Build passphrases from unrelated random words rather than single dictionary words or short complex strings.",
            "options": [("A multi-word random passphrase", True),
                        ("My pet's name plus my birth year", False)],
        },
        {
            "scenario_type": "password", "difficulty": "hard",
            "prompt": "A website you rarely use was breached. You used the same password there as on your primary email.",
            "question_text": "What's the correct priority order of action?",
            "hint_text": "Which account matters more if compromised — the rarely used site, or your primary email (which can reset everything else)?",
            "correct_explanation": "Your primary email is often the 'master key' to resetting other accounts — it should be secured (password changed, MFA enabled) immediately, ahead of the breached site itself.",
            "warning_signs": "Password reuse across a low-value and a high-value (email) account",
            "recommended_action": "Immediately change your email password (and enable MFA), then update the password everywhere it was reused.",
            "options": [("Change the breached site's password first, deal with email later", False),
                        ("Immediately secure my email first, since it can reset other accounts", True)],
        },
        {
            "scenario_type": "password", "difficulty": "hard",
            "prompt": "An app asks you to log in \"with your email password\" instead of creating a separate account.",
            "question_text": "What's the security concern with reusing your primary email password on a third-party app?",
            "hint_text": "Think about how much trust you're extending to that third-party app.",
            "correct_explanation": "Typing your primary email password into an unrelated third-party app means that app (or a breach of it) could expose the password that also protects your email — your most sensitive account.",
            "warning_signs": "Third-party app requesting your primary email's actual password\nNo official 'Sign in with' OAuth flow mentioned",
            "recommended_action": "Never type your email password into a third-party app. Use official 'Sign in with Google/Apple/etc.' (OAuth) options instead, or a separate unique password.",
            "options": [("It's fine, it saves time creating a new account", False),
                        ("It risks exposing my email password to an unrelated app", True)],
        },
    ],
    "scam_spotter": [
        {
            "scenario_type": "sms", "difficulty": "easy",
            "prompt": "SMS: \"NovaBank Alert: Your a/c will be BLOCKED today. Update KYC now: hxxp://novabank-kyc.example-scam.tk\"",
            "question_text": "How should you handle this SMS?",
            "hint_text": "Real banks don't threaten to block accounts via unsolicited SMS links.",
            "correct_explanation": "This is a classic KYC-scam SMS: urgency, threat of account blocking, and a suspicious short/unfamiliar link.",
            "warning_signs": "Urgent threat (account blocking)\nUnfamiliar shortened/suspicious domain\nRequests immediate action via SMS link",
            "recommended_action": "Don't click the link. Contact your bank directly using their official app or the number on your card.",
            "options": [("Click the link right away to avoid losing my account", False),
                        ("Ignore the link and contact my bank directly through official channels", True)],
        },
        {
            "scenario_type": "sms", "difficulty": "easy",
            "prompt": "WhatsApp message from unknown number: \"Hi mom, I lost my phone, this is my new number. Can you send money urgently, I'll explain later?\"",
            "question_text": "What's the safest response?",
            "hint_text": "This is a well-known 'family emergency' impersonation scam.",
            "correct_explanation": "This is the well-known 'Hi Mom/Dad' scam — impersonating a family member on a new number and creating urgency to bypass normal verification.",
            "warning_signs": "Unknown number claiming to be a family member\nUrgency, avoids explaining\nRequests money transfer",
            "recommended_action": "Call your actual family member on their known number before sending any money.",
            "options": [("Send the money right away since it's urgent", False),
                        ("Call the family member's known number to verify first", True)],
        },
        {
            "scenario_type": "sms", "difficulty": "medium",
            "prompt": "SMS: \"Congratulations! You've won a QuickShop gift voucher worth $500. Claim here: hxxp://quickshop-rewards.example-scam.top\"",
            "question_text": "You never entered any contest. What should you do?",
            "hint_text": "Can you win a contest you never entered?",
            "correct_explanation": "You can't win a contest you never entered — unsolicited prize notifications are a very common scam lure to get you to click a malicious link or pay a 'claim fee'.",
            "warning_signs": "Unsolicited prize/reward claim\nYou never entered any contest\nSuspicious link domain",
            "recommended_action": "Don't click the link. Delete the message.",
            "options": [("Click the link to claim my prize", False),
                        ("Ignore it — I never entered any contest", True)],
        },
        {
            "scenario_type": "call_transcript", "difficulty": "medium",
            "prompt": "Caller: \"This is tech support. We've detected a virus on your computer. Please install this remote-access tool so we can fix it for you.\"",
            "question_text": "What's the correct response to this unsolicited call?",
            "hint_text": "Do legitimate tech companies proactively call you about viruses?",
            "correct_explanation": "Legitimate tech companies do not make unsolicited calls about viruses on your device — this is a classic tech-support scam designed to gain remote access to your computer.",
            "warning_signs": "Unsolicited call\nClaims to have detected a problem remotely\nAsks you to install remote-access software",
            "recommended_action": "Hang up. Never install remote-access software at the request of an unsolicited caller.",
            "options": [("Install the tool so they can fix the virus", False),
                        ("Hang up — this is a tech-support scam pattern", True)],
        },
        {
            "scenario_type": "sms", "difficulty": "medium",
            "prompt": "SMS: \"Your QuickShop package couldn't be delivered due to unpaid customs fee of $2.99. Pay here: hxxp://quickshop-fees.example-scam.info\"",
            "question_text": "You weren't expecting a package. What should you do?",
            "hint_text": "Small, plausible-sounding fees are a common scam trick to lower your guard.",
            "correct_explanation": "Small 'customs fee' or 'redelivery fee' scams rely on the low amount seeming not worth questioning — but they're designed to harvest card details via a fake payment page.",
            "warning_signs": "Unexpected package you didn't order\nSmall 'too easy to ignore' fee\nSuspicious payment link",
            "recommended_action": "Don't pay via the link. Check tracking directly with the courier using an order number you actually have.",
            "options": [("Pay the small fee since it's not much money", False),
                        ("Don't pay — verify directly with the courier instead", True)],
        },
        {
            "scenario_type": "whatsapp", "difficulty": "hard",
            "prompt": "WhatsApp: \"This is HR. Due to a system update, please confirm your salary account details and Aadhaar number by replying here to avoid payment delay.\"",
            "question_text": "Your actual HR usually uses official email, not WhatsApp, for this. What now?",
            "hint_text": "Notice the channel mismatch — is this how your real HR normally communicates sensitive requests?",
            "correct_explanation": "A shift to an informal channel (WhatsApp) for a sensitive request (bank + national ID details) that your real HR normally handles via official email/portal is a strong impersonation red flag.",
            "warning_signs": "Unusual channel for a sensitive HR request\nRequests bank + government ID details\nCreates urgency (payment delay)",
            "recommended_action": "Verify directly with HR through their official email or portal before sharing any sensitive information.",
            "options": [("Reply with the details to avoid a payment delay", False),
                        ("Verify with HR through official channels first", True)],
        },
        {
            "scenario_type": "sms", "difficulty": "hard",
            "prompt": "SMS: \"NovaBank: A payment of $499 has been made from your account. If this wasn't you, call us immediately at +1-555-0134-9981 to cancel.\"",
            "question_text": "The number isn't your bank's usual number. What's the safest move?",
            "hint_text": "Calling a number FROM the suspicious message defeats the purpose of verifying it.",
            "correct_explanation": "This creates panic about an unauthorized payment and provides a fake 'support' number — calling it just hands you to the scammer directly. Always use a number you already know is real.",
            "warning_signs": "Panic-inducing fake transaction alert\nProvides its own phone number to call\nUnfamiliar/unverified number",
            "recommended_action": "Don't call the number in the message. Call your bank using the number on your card or their official app/website.",
            "options": [("Call the number in the message right away", False),
                        ("Call my bank using a number I already know is correct", True)],
        },
        {
            "scenario_type": "sms", "difficulty": "hard",
            "prompt": "SMS: \"Your electricity bill payment failed. Service will be disconnected tonight. Pay now via this link to avoid disconnection: hxxp://power-billing.example-scam.click\"",
            "question_text": "You did pay your bill through the utility's app already. What's happening here?",
            "hint_text": "Utility-disconnection scams spike right before due dates because they're plausible and time-pressured.",
            "correct_explanation": "This is a utility-disconnection scam — it exploits urgency around a real, common bill category and a suspicious link, regardless of whether you already paid.",
            "warning_signs": "Urgent disconnection threat\nSuspicious payment link\nNo account-specific details provided",
            "recommended_action": "Don't click the link. Check your account status directly through the utility's official app or website.",
            "options": [("Pay through the link immediately to avoid disconnection", False),
                        ("Check my account directly on the utility's official app instead", True)],
        },
    ],
    "cyber_escape": [
        {
            "scenario_type": "mixed", "difficulty": "medium",
            "prompt": "STAGE 1 — Email: From: alerts@novabank-alerts.info | Subject: Suspicious login blocked, verify identity now: hxxp://novabank.secure-check.top/verify",
            "question_text": "First, assess the sender. Is this email trustworthy?",
            "hint_text": "Check the sender domain against what you learned in Level 1.",
            "correct_explanation": "The sender domain doesn't match NovaBank's real domain, and it uses urgency plus a verification link — the same phishing pattern from Level 1.",
            "warning_signs": "Suspicious sender domain\nUrgency\nVerification link",
            "recommended_action": "Do not click. Move to inspecting the link itself before doing anything else.",
            "options": [("This is a phishing email", True), ("This is a legitimate bank alert", False)],
        },
        {
            "scenario_type": "mixed", "difficulty": "medium",
            "prompt": "STAGE 2 — You inspect the link before clicking: hxxp://novabank.secure-check.top/verify",
            "question_text": "What's the real domain being used here?",
            "hint_text": "Read the domain from right to left, ignoring the 'novabank' prefix.",
            "correct_explanation": "The real domain is 'secure-check.top' — 'novabank' is just a misleading subdomain-style prefix, exactly like the URL Detective lessons covered.",
            "warning_signs": "Brand name used as a fake subdomain prefix\nUnusual TLD (.top)",
            "recommended_action": "Confirm this is not NovaBank's real domain, and do not proceed to enter any information.",
            "options": [("novabank.com", False), ("secure-check.top", True)],
        },
        {
            "scenario_type": "mixed", "difficulty": "medium",
            "prompt": "STAGE 3 — A pop-up on the fake page asks you to \"confirm your identity\" by entering your NovaBank password.",
            "question_text": "What do you do?",
            "hint_text": "You already identified this as a fake domain in the last stage.",
            "correct_explanation": "Since the domain was already confirmed fake, entering your real password here would hand it directly to an attacker.",
            "warning_signs": "Password entry requested on a confirmed look-alike domain",
            "recommended_action": "Close the page immediately. Do not enter your password anywhere on this site.",
            "options": [("Enter my real password to see what happens", False),
                        ("Close the page immediately without entering anything", True)],
        },
        {
            "scenario_type": "mixed", "difficulty": "medium",
            "prompt": "STAGE 4 — Minutes later, an SMS arrives: \"NovaBank: Your OTP is 482913. Do not share this with anyone, including bank staff.\" Then a call comes in: \"This is NovaBank fraud prevention, please read us the OTP you just received to cancel a suspicious transaction.\"",
            "question_text": "Should you read out the OTP to the caller?",
            "hint_text": "Re-read the SMS itself — what does it explicitly say?",
            "correct_explanation": "The SMS itself warns not to share the OTP with anyone, including bank staff — real banks never ask you to read out an OTP over a call. This is a live OTP-theft attempt following the earlier phishing stages.",
            "warning_signs": "Caller requests OTP over the phone\nContradicts the SMS's own explicit warning\nFollows immediately after a phishing attempt",
            "recommended_action": "Do not share the OTP. Hang up and contact your bank using a verified number.",
            "options": [("Read the OTP so they can cancel the transaction", False),
                        ("Refuse and hang up — never share an OTP over a call", True)],
        },
        {
            "scenario_type": "mixed", "difficulty": "hard",
            "prompt": "STAGE 5 — You decide to check your account directly. On the real NovaBank app, you notice you've been using the same password here as on your personal email for the last 2 years.",
            "question_text": "Given everything that just happened, what should you prioritize?",
            "hint_text": "Think about Account Guardian's lesson on password reuse and what to secure first.",
            "correct_explanation": "Given the phishing attempt just occurred, and password reuse is confirmed, both the bank account AND email need new unique passwords — with email prioritized since it can reset other accounts.",
            "warning_signs": "Password reuse across sensitive accounts, discovered right after a phishing attempt",
            "recommended_action": "Change your email password first (enabling MFA), then change your NovaBank password to something unique, and enable MFA there too.",
            "options": [("Nothing — no password was actually entered, so it's fine", False),
                        ("Change both passwords to unique ones and enable MFA, prioritizing email", True)],
        },
        {
            "scenario_type": "mixed", "difficulty": "hard",
            "prompt": "STAGE 6 — You want to warn a friend. You draft a message describing exactly what happened, including the fake domain and the phone number that called you.",
            "question_text": "What's a responsible way to also handle this at an official level?",
            "hint_text": "Beyond warning friends personally, what official step is available?",
            "correct_explanation": "Beyond personally warning contacts, reporting the phishing domain and the fraudulent call to the official cybercrime reporting channel helps get it taken down and logged for others.",
            "warning_signs": "N/A — this is about the correct response, not a threat",
            "recommended_action": "Use the Official Resources page to report the suspicious URL and phone number through the official cybercrime portal.",
            "options": [("Only warn friends privately, no need to report it officially", False),
                        ("Warn friends AND report it through the official cybercrime portal", True)],
        },
        {
            "scenario_type": "mixed", "difficulty": "hard",
            "prompt": "STAGE 7 — Reflecting on the whole scenario, which single moment was the most important point where the attack could have been stopped completely?",
            "question_text": "Pick the earliest effective stopping point.",
            "hint_text": "The earlier you catch it, the less damage occurs overall.",
            "correct_explanation": "Recognizing the phishing email at Stage 1 (before even clicking the link) is the earliest and most effective point to stop the entire attack chain — every later stage only existed because that first step wasn't caught.",
            "warning_signs": "N/A — this is a reflection question",
            "recommended_action": "The earlier a threat is recognized in the chain, the less exposure and cleanup is required — always start with sender/domain scrutiny.",
            "options": [("Stage 1 — recognizing the phishing email itself", True),
                        ("Stage 4 — refusing to share the OTP", False)],
        },
        {
            "scenario_type": "mixed", "difficulty": "hard",
            "prompt": "STAGE 8 (FINAL) — You've secured your accounts, reported the phishing domain and phone number, and warned your contacts.",
            "question_text": "Have you successfully escaped the scam?",
            "hint_text": "Review: did you avoid entering credentials, avoid sharing the OTP, secure your passwords, and report it?",
            "correct_explanation": "By recognizing the phishing email, avoiding the fake login page, refusing to share the OTP, securing reused passwords, and reporting the incident, you completed every defensive step correctly.",
            "warning_signs": "N/A — this is the successful conclusion",
            "recommended_action": "Great work — this is exactly the PREVENT → DETECT → RESPOND cycle CyberShield teaches.",
            "options": [("Yes — CYBER ESCAPE SUCCESSFUL", True),
                        ("No, more steps were needed", False)],
        },
    ],
}
